# Build settings
permalink   : /:categories/:year/:title/
markdown    : kramdown
highlighter : pygments

paginate: 2 #6
comments: true
paginate_path: "/page/:num"

source: source
destination: _site
sass:
  sass_dir: _scss
  style: expanded # compressed

# SEO settings
title: end2end
description: "A free Jekyll theme for download"
keywords: "Jekyll, theme, free, download, SEO, blog, web"
url: http://nandomoreira.me
# baseurl: "/ens2end"
baseurl: ""

# google_analytics: UA-52446115-1
repo: http://github.com/nandomoreirame/end2end
disqus_shortname: "fernandomoreira"

# Author settings
author:
  name      : Fernando Moreira
  image     : /assets/images/author.jpg
  email     : nandomoreira.me@gmail.com
  url       : http://nandomoreira.me
  facebook  : http://facebook.com/fernando.dev
  twitter   : http://twitter.com/nandomoreirame
  instagram : http://instagram.com/nandomoreira.me
  github    : http://github.com/nandomoreirame
  linkedin  : http://linkedin.com/in/nandomoreirame
  bio       : "Desenvolvedor Front-end/Wordpress entusiasta de performance, design responsivo e usabilidade, sempre em busca do melhor projeto e de um bom café."

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: resume
    title: Resume
  - slug: skills
    title: Skills
  - slug: blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]